#!/usr/bin/env python3
"""
reporting/navigator/generate_navigator_layer.py

OBSIDIAN PROTOCOL — ATT&CK Navigator Layer + Detection Coverage Matrix

This script produces a REAL JSON file in the official MITRE ATT&CK
Navigator Layer format (v4.5). This file can be uploaded directly at
https://mitre-attack.github.io/attack-navigator/ via "Open Existing
Layer -> Upload from local".

Format reference: mitre-attack/attack-navigator repo, layers/spec/v4.5/layerformat.md

Color coding (based on Purple Team coverage):
  - Green: technique was performed AND caught by WARDEN
  - Red:   technique was performed BUT NOT caught (detection gap)
  - Grey:  technique was not used in this operation (unscored)

Input: purple-team/output/coverage_results.json
Output: reporting/navigator/obsidian_protocol_layer.json
"""

import json
import os

COVERAGE_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "purple-team", "output", "coverage_results.json"
)
OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "obsidian_protocol_layer.json")

COLOR_DETECTED = "#2ecc71"      # green - detected
COLOR_MISSED = "#e74c3c"        # red - missed (detection gap)


def build_layer(coverage_results: list) -> dict:
    """Produces a dict in the official ATT&CK Navigator v4.5 layer format."""

    techniques = []
    seen_techniques = {}  # technique_id -> most current/representative result

    for r in coverage_results:
        tid = r.get("mitre_technique")
        if not tid:
            continue

        # The same technique may be used in more than one step (e.g.
        # T1190 in both recon and initial access) - count it as
        # "detected" if caught at least once, "missed" if never caught
        if tid not in seen_techniques:
            seen_techniques[tid] = {"detected": False, "steps": []}
        seen_techniques[tid]["steps"].append(r["attack_step"])
        if r.get("detected"):
            seen_techniques[tid]["detected"] = True

    for tid, info in seen_techniques.items():
        techniques.append({
            "techniqueID": tid,
            "score": 100 if info["detected"] else 0,
            "color": COLOR_DETECTED if info["detected"] else COLOR_MISSED,
            "comment": (
                f"Used in the OBSIDIAN PROTOCOL operation: {'; '.join(info['steps'])}. "
                f"Status: {'caught by WARDEN' if info['detected'] else 'DETECTION GAP - not caught'}"
            ),
            "showSubtechniques": True,
        })

    layer = {
        "name": "OBSIDIAN PROTOCOL — Detection Coverage",
        "versions": {
            "attack": "17",
            "navigator": "5.1.0",
            "layer": "4.5",
        },
        "domain": "enterprise-attack",
        "description": (
            "MITRE ATT&CK technique coverage map for the VECTOR-I "
            "(CVE-2021-41773/42013) and VECTOR-II (CVE-2021-4034) attack "
            "chain, based on Purple Team validation results. Green = "
            "caught by the WARDEN module, Red = detection gap (not caught)."
        ),
        "filters": {
            "platforms": ["Linux"],
        },
        "sorting": 0,
        "layout": {
            "layout": "side",
            "showName": True,
            "showID": True,
            "showAggregateScores": False,
            "countUnscored": False,
        },
        "hideDisabled": False,
        "techniques": techniques,
        "gradient": {
            "colors": [COLOR_MISSED, COLOR_DETECTED],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [
            {"label": "Detected (WARDEN signal present)", "color": COLOR_DETECTED},
            {"label": "Detection Gap (no signal)", "color": COLOR_MISSED},
        ],
        "metadata": [
            {"name": "Project", "value": "OBSIDIAN PROTOCOL"},
            {"name": "Generated", "value": "automatic - generate_navigator_layer.py"},
        ],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#1a1a2e",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
    }
    return layer


def build_coverage_matrix_markdown(coverage_results: list) -> str:
    """
    In addition to the Navigator's visual/JSON format, also produces a
    Markdown table that can be viewed directly in the README — a quick
    summary without needing to upload the Navigator file.
    """
    seen = {}
    for r in coverage_results:
        tid = r.get("mitre_technique")
        if not tid:
            continue
        if tid not in seen:
            seen[tid] = {"detected": False, "cve": r.get("cve"), "vector": r.get("vector")}
        if r.get("detected"):
            seen[tid]["detected"] = True

    lines = [
        "# Detection Coverage Matrix",
        "",
        "> Automatically generated by: `reporting/navigator/generate_navigator_layer.py`",
        "",
        "| MITRE Technique | Vector | CVE | Status |",
        "|---|---|---|---|",
    ]
    for tid, info in sorted(seen.items()):
        status = "✅ Detected" if info["detected"] else "❌ Detection Gap"
        lines.append(f"| {tid} | {info['vector']} | {info['cve'] or '-'} | {status} |")

    total = len(seen)
    detected_count = sum(1 for v in seen.values() if v["detected"])
    lines.append("")
    lines.append(f"**Total coverage: {detected_count}/{total} techniques ({detected_count/total*100:.0f}%)**" if total else "No data")
    lines.append("")
    lines.append("For the visual heatmap, upload `obsidian_protocol_layer.json` to "
                  "[ATT&CK Navigator](https://mitre-attack.github.io/attack-navigator/).")

    return "\n".join(lines)


def main():
    if not os.path.exists(COVERAGE_PATH):
        print(f"[!] Coverage data not found: {COVERAGE_PATH}")
        print("[!] Run first: python3 purple-team/validate.py purple-team/my_attack_log.json")
        return

    with open(COVERAGE_PATH) as f:
        coverage_results = json.load(f)

    layer = build_layer(coverage_results)
    with open(OUTPUT_PATH, "w") as f:
        json.dump(layer, f, indent=2, ensure_ascii=False)
    print(f"[+] ATT&CK Navigator layer file generated: {OUTPUT_PATH}")
    print(f"[+] To upload: https://mitre-attack.github.io/attack-navigator/ -> Open Existing Layer -> Upload from local")

    matrix_md = build_coverage_matrix_markdown(coverage_results)
    matrix_path = os.path.join(os.path.dirname(__file__), "..", "..", "docs", "detection-coverage-matrix.md")
    with open(matrix_path, "w") as f:
        f.write(matrix_md)
    print(f"[+] Markdown coverage matrix generated: {matrix_path}")


if __name__ == "__main__":
    main()
