#!/usr/bin/env python3
"""
telemetry-gap/gap_analysis.py

OBSIDIAN PROTOCOL — Telemetry Gap Analyzer

REAL-WORLD PROBLEM: Organizations generally know what they ARE
monitoring, but not what they AREN'T. Every missing telemetry source
creates blindness in the MITRE techniques that source would have
covered.

SOLUTION: this engine uses a known "telemetry source -> MITRE tactics
it covers" mapping table, checks each source the environment is or
isn't currently collecting, and reports which tactics are BLIND.
"""

import json
import os
from dataclasses import dataclass, asdict

BASE_DIR = os.path.join(os.path.dirname(__file__), "..")
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "output")

# Telemetry source -> which MITRE tactics it gives visibility into.
TELEMETRY_SOURCE_COVERAGE = {
    "Apache/Web Server Access Log": {
        "tactics": ["Initial Access", "Execution"],
        "collected": True,
    },
    "auditd": {
        "tactics": ["Privilege Escalation", "Persistence", "Execution"],
        "collected": True,
    },
    "eBPF (syscall tracing)": {
        "tactics": ["Privilege Escalation", "Execution", "Defense Evasion"],
        "collected": True,
    },
    "DNS Query Logs": {
        "tactics": ["Command and Control", "Exfiltration"],
        "collected": False,
    },
    "Sysmon (Windows)": {
        "tactics": ["Execution", "Persistence", "Lateral Movement", "Defense Evasion"],
        "collected": False,
    },
    "EDR (Endpoint Detection & Response)": {
        "tactics": ["Defense Evasion", "Credential Access", "Discovery", "Collection"],
        "collected": False,
    },
    "NetFlow / Network Traffic Metadata": {
        "tactics": ["Lateral Movement", "Command and Control", "Exfiltration", "Discovery"],
        "collected": False,
    },
    "Cloud Audit Logs (e.g. AWS CloudTrail)": {
        "tactics": ["Initial Access", "Persistence", "Privilege Escalation", "Collection"],
        "collected": False,
    },
}


@dataclass
class GapAnalysisResult:
    visible_tactics: list
    blind_tactics: list
    partial_tactics: list
    source_status: dict
    recommendations: list


def analyze_gaps() -> GapAnalysisResult:
    tactic_visibility = {}
    tactic_total_sources = {}

    source_status = {}
    for source, info in TELEMETRY_SOURCE_COVERAGE.items():
        collected = info["collected"]
        source_status[source] = {"collected": collected, "tactics": info["tactics"]}

        for tactic in info["tactics"]:
            tactic_total_sources[tactic] = tactic_total_sources.get(tactic, 0) + 1
            if collected:
                tactic_visibility[tactic] = tactic_visibility.get(tactic, 0) + 1

    visible, blind, partial = [], [], []
    for tactic, total in tactic_total_sources.items():
        visible_count = tactic_visibility.get(tactic, 0)
        if visible_count == 0:
            blind.append(tactic)
        elif visible_count < total:
            partial.append(tactic)
        else:
            visible.append(tactic)

    recommendations = []
    missing_sources = [s for s, info in TELEMETRY_SOURCE_COVERAGE.items() if not info["collected"]]
    missing_sources.sort(
        key=lambda s: -sum(1 for t in TELEMETRY_SOURCE_COVERAGE[s]["tactics"] if t in blind)
    )
    for s in missing_sources[:3]:
        covered_blind = [t for t in TELEMETRY_SOURCE_COVERAGE[s]["tactics"] if t in blind]
        if covered_blind:
            recommendations.append(
                f"Start collecting '{s}' -> closes these blind tactics: {', '.join(covered_blind)}"
            )

    return GapAnalysisResult(
        visible_tactics=sorted(visible),
        blind_tactics=sorted(blind),
        partial_tactics=sorted(partial),
        source_status=source_status,
        recommendations=recommendations,
    )


def print_report(result: GapAnalysisResult):
    print("=" * 70)
    print("  OBSIDIAN PROTOCOL — TELEMETRY GAP ANALYZER")
    print("=" * 70)

    print("\n  CURRENT VISIBILITY (Source Status)\n")
    for source, status in result.source_status.items():
        mark = "✓" if status["collected"] else "✗"
        print(f"  {mark}  {source:<42} -> {', '.join(status['tactics'])}")

    print(f"\n  FULLY VISIBLE TACTICS ({len(result.visible_tactics)}): {', '.join(result.visible_tactics) or '-'}")
    print(f"  PARTIALLY VISIBLE TACTICS ({len(result.partial_tactics)}): {', '.join(result.partial_tactics) or '-'}")
    print(f"  BLIND TACTICS ({len(result.blind_tactics)}): {', '.join(result.blind_tactics) or '-'}")

    print("\n  RECOMMENDED COLLECTION (Prioritized)\n")
    for i, rec in enumerate(result.recommendations, 1):
        print(f"  {i}. {rec}")


def build_markdown(result: GapAnalysisResult) -> str:
    lines = [
        "# Telemetry Gap Analysis",
        "",
        "> Automatically generated by: `telemetry-gap/gap_analysis.py`",
        "",
        "## Current Visibility",
        "",
        "| Source | Status | Tactics Covered |",
        "|---|---|---|",
    ]
    for source, status in result.source_status.items():
        mark = "✓" if status["collected"] else "✗"
        lines.append(f"| {source} | {mark} | {', '.join(status['tactics'])} |")

    lines += [
        "",
        f"**Fully visible tactics:** {', '.join(result.visible_tactics) or '-'}",
        f"**Partially visible tactics:** {', '.join(result.partial_tactics) or '-'}",
        f"**Blind tactics:** {', '.join(result.blind_tactics) or '-'}",
        "",
        "## Recommended Collection",
        "",
    ]
    for i, rec in enumerate(result.recommendations, 1):
        lines.append(f"{i}. {rec}")

    return "\n".join(lines)


def main():
    result = analyze_gaps()
    print_report(result)

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    json_path = os.path.join(OUTPUT_DIR, "telemetry_gap.json")
    with open(json_path, "w") as f:
        json.dump(asdict(result), f, indent=2, ensure_ascii=False)

    md_path = os.path.join(BASE_DIR, "docs", "telemetry-gap-analysis.md")
    with open(md_path, "w") as f:
        f.write(build_markdown(result))

    print(f"\n[+] JSON: {json_path}")
    print(f"[+] Markdown: {md_path}")


if __name__ == "__main__":
    main()
